class Honey:
    def h(self):
        print("Honey is generated by honeybees.")

class Food(Honey):
    def f(self):
        print("Honey is a healthy food.")

class Medicine(Honey):
    def m(self):
        print("Honey is also used as a medicine.")

obj1 = Food()
obj2 = Medicine()
obj1.h()
obj1.f()
obj2.h()
obj2.m()               